<?php
// Theme Option Page Initializing
add_action('acf/init', 'ramdhanu_acf_options_init');
function ramdhanu_acf_options_init() {
	if( function_exists("acf_add_options_page") ) {
		acf_add_options_page(array(
			'page_title' => 'Theme Options',
			'menu_title' => 'Theme Options',
			'menu_slug'  => 'theme-options',
			'icon_url' => 'dashicons-screenoptions',
			'capability' => 'edit_posts'
		));
	}
}

// Theme Option Page Initializing
// if( function_exists("acf_add_options_page") ) {
// 	acf_add_options_page(array(
// 		'page_title' => 'Theme Slider',
// 		'menu_title' => 'Theme Slider',
// 		'menu_slug'  => 'slider-options',
// 		'icon_url' => 'dashicons-images-alt',
// 		'capability' => 'edit_posts'
// 	));
// }


// Theme Option Settings Exported From ACF
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6a12e612c865a',
	'title' => 'About Us Page',
	'fields' => array(
		array(
			'key' => 'field_6a12e613c183e',
			'label' => 'Images & Video',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a12e73be4a9e',
			'label' => 'Featured Image 1',
			'name' => 'featured_image_1',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6a12e753e4a9f',
			'label' => 'Featured Image 2',
			'name' => 'featured_image_2',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6a12e758e4aa0',
			'label' => 'Video Url',
			'name' => 'video_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template/about.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a12dedfcc6dc',
	'title' => 'Contact Us Page',
	'fields' => array(
		array(
			'key' => 'field_6a12dee0fd937',
			'label' => 'Google Map Iframe',
			'name' => 'google_map_iframe',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template/contact.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a12e1a8bfcb5',
	'title' => 'Gallery',
	'fields' => array(
		array(
			'key' => 'field_6a12e1a9ebd3f',
			'label' => 'Gallery',
			'name' => 'gallery',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'insert' => 'append',
			'preview_size' => 'medium',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'event',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a13e5beeb2d2',
	'title' => 'Home',
	'fields' => array(
		array(
			'key' => 'field_6a13e5bf0878a',
			'label' => 'About Us',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a13e5f80d9b0',
			'label' => 'About Image 1',
			'name' => 'about_image_1',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6a13e6220d9b1',
			'label' => 'About Image 2',
			'name' => 'about_image_2',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6a13e6250d9b2',
			'label' => 'About Image 3',
			'name' => 'about_image_3',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 0,
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_6a33987e5e1c2',
			'label' => 'About Video Url',
			'name' => 'about_video_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a13e6280d9b3',
			'label' => 'About Section Title',
			'name' => 'about_section_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a13e6410d9b4',
			'label' => 'About Us Title',
			'name' => 'about_us_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a13e64b0d9b5',
			'label' => 'About Us Texts',
			'name' => 'about_us_texts',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a13e65f0d9b7',
			'label' => 'Mission & Vision',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a13e66c0d9b8',
			'label' => 'Mission Texts',
			'name' => 'mission_texts',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a13e6760d9b9',
			'label' => 'Vision Texts',
			'name' => 'vision_texts',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a13e68f6a9a8',
			'label' => 'Projects Section',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a13e69d6a9a9',
			'label' => 'Project Title Small',
			'name' => 'project_title_small',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a13e6b36a9aa',
			'label' => 'Project Title',
			'name' => 'project_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a13e7bb37095',
			'label' => 'All Projects',
			'name' => 'all_projects',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6a13e7d437096',
					'label' => 'Project Image',
					'name' => 'project_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
					'parent_repeater' => 'field_6a13e7bb37095',
				),
				array(
					'key' => 'field_6a13e7ed37097',
					'label' => 'Project Title',
					'name' => 'project_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a13e7bb37095',
				),
				array(
					'key' => 'field_6a13e7f537098',
					'label' => 'Project Texts',
					'name' => 'project_texts',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a13e7bb37095',
				),
				array(
					'key' => 'field_6a13e7fd37099',
					'label' => 'Project Page Url',
					'name' => 'project_page_url',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'allow_in_bindings' => 0,
					'parent_repeater' => 'field_6a13e7bb37095',
				),
			),
		),
		array(
			'key' => 'field_6a13e81b53eef',
			'label' => 'CTA Area',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a13e82953ef0',
			'label' => 'CTA Small Title',
			'name' => 'cta_small_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a13e83453ef1',
			'label' => 'CTA Title',
			'name' => 'cta_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a13e84b162c8',
			'label' => 'Video Section',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a13e8cb162c9',
			'label' => 'Video Section Title Small',
			'name' => 'video_section_title_small',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a13e8e5162ca',
			'label' => 'Video Section Main Title',
			'name' => 'video_section_main_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a13e8f4162cb',
			'label' => 'All Videos',
			'name' => 'all_videos',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6a13e93b162cc',
					'label' => 'Video Url',
					'name' => 'video_url',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a13e8f4162cb',
				),
				array(
					'key' => 'field_6a13e980162cd',
					'label' => 'Video Image',
					'name' => 'video_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
					'parent_repeater' => 'field_6a13e8f4162cb',
				),
			),
		),
		array(
			'key' => 'field_6a13e9c292b25',
			'label' => 'Counter',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a13e9cf92b26',
			'label' => 'All Counter Item',
			'name' => 'all_counter_item',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6a13e9fa92b27',
					'label' => 'Counter Icon',
					'name' => 'counter_icon',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'solid',
						1 => 'regular',
						2 => 'brands',
					),
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 1,
					'allow_in_bindings' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
					'parent_repeater' => 'field_6a13e9cf92b26',
				),
				array(
					'key' => 'field_6a13ea2792b28',
					'label' => 'Counter Number',
					'name' => 'counter_number',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a13e9cf92b26',
				),
				array(
					'key' => 'field_6a13ea3392b29',
					'label' => 'Counter Title',
					'name' => 'counter_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a13e9cf92b26',
				),
			),
		),
		array(
			'key' => 'field_6a13ea4d63e7e',
			'label' => 'Team Member',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a13ea6063e7f',
			'label' => 'Team Members',
			'name' => 'team_members',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6a13ea9663e80',
					'label' => 'Member Photo',
					'name' => 'member_photo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
					'parent_repeater' => 'field_6a13ea6063e7f',
				),
				array(
					'key' => 'field_6a13eaab63e81',
					'label' => 'Member Name',
					'name' => 'member_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a13ea6063e7f',
				),
				array(
					'key' => 'field_6a13eab563e82',
					'label' => 'Member Designation',
					'name' => 'member_designation',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a13ea6063e7f',
				),
				array(
					'key' => 'field_6a13eac163e83',
					'label' => 'Member Descriptions',
					'name' => 'member_descriptions',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
					'parent_repeater' => 'field_6a13ea6063e7f',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a12e376ec92a',
	'title' => 'Newsletter',
	'fields' => array(
		array(
			'key' => 'field_6a12e377f21d0',
			'label' => 'Newsletter',
			'name' => 'newsletter',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6a12e3de9e81b',
					'label' => 'Newsletter Title',
					'name' => 'newsletter_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a12e377f21d0',
				),
				array(
					'key' => 'field_6a12e3e99e81c',
					'label' => 'Newsletter File',
					'name' => 'newsletter_file',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'parent_repeater' => 'field_6a12e377f21d0',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template/newsletter.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a33cdc88d90d',
	'title' => 'Project Page',
	'fields' => array(
		array('key' => 'field_pp_tab_banner', 'label' => 'Banner Section', 'name' => '', 'type' => 'tab'),
		array('key' => 'field_pp_banner_bg', 'label' => 'Banner Background Image', 'name' => 'banner_background_image', 'type' => 'image', 'return_format' => 'array'),
		
		array('key' => 'field_pp_tab_issue', 'label' => 'The Issue Section', 'name' => '', 'type' => 'tab'),
		array('key' => 'field_pp_issue_sub', 'label' => 'Sub Title', 'name' => 'issue_sub_title', 'type' => 'text'),
		array('key' => 'field_pp_issue_title', 'label' => 'Title', 'name' => 'issue_title', 'type' => 'text'),
		array('key' => 'field_pp_issue_content', 'label' => 'Content', 'name' => 'issue_content', 'type' => 'wysiwyg'),
		array('key' => 'field_pp_issue_highlight', 'label' => 'Highlight (Quote)', 'name' => 'issue_highlight', 'type' => 'textarea'),
		array('key' => 'field_pp_issue_stats', 'label' => 'Stats', 'name' => 'issue_stats', 'type' => 'repeater', 'sub_fields' => array(
			array('key' => 'field_pp_issue_stat_num', 'label' => 'Number', 'name' => 'number', 'type' => 'text'),
			array('key' => 'field_pp_issue_stat_label', 'label' => 'Label', 'name' => 'label', 'type' => 'text'),
		)),
		array('key' => 'field_pp_issue_image', 'label' => 'Image', 'name' => 'issue_image', 'type' => 'image', 'return_format' => 'array'),
		array('key' => 'field_pp_issue_video', 'label' => 'Video URL', 'name' => 'issue_video_url', 'type' => 'text'),
		
		array('key' => 'field_pp_tab_work', 'label' => 'Our Work Section', 'name' => '', 'type' => 'tab'),
		array('key' => 'field_pp_work_sub', 'label' => 'Sub Title', 'name' => 'work_sub_title', 'type' => 'text'),
		array('key' => 'field_pp_work_title', 'label' => 'Title', 'name' => 'work_title', 'type' => 'text'),
		array('key' => 'field_pp_work_desc', 'label' => 'Description', 'name' => 'work_description', 'type' => 'textarea'),
		array('key' => 'field_pp_work_activities', 'label' => 'Activities', 'name' => 'work_activities', 'type' => 'repeater', 'sub_fields' => array(
			array('key' => 'field_pp_wa_icon', 'label' => 'Icon Class', 'name' => 'icon_class', 'type' => 'text'),
			array('key' => 'field_pp_wa_title', 'label' => 'Title', 'name' => 'title', 'type' => 'text'),
			array('key' => 'field_pp_wa_desc', 'label' => 'Description', 'name' => 'description', 'type' => 'textarea'),
		)),
		
		array('key' => 'field_pp_tab_gallery', 'label' => 'Gallery Section', 'name' => '', 'type' => 'tab'),
		array('key' => 'field_pp_gallery_sub', 'label' => 'Sub Title', 'name' => 'gallery_sub_title', 'type' => 'text'),
		array('key' => 'field_pp_gallery_title', 'label' => 'Title', 'name' => 'gallery_title', 'type' => 'text'),
		array('key' => 'field_pp_project_gallery', 'label' => 'Project Gallery', 'name' => 'project_gallery', 'type' => 'gallery', 'return_format' => 'array'),
		
		array('key' => 'field_pp_tab_impact', 'label' => 'Impact Section', 'name' => '', 'type' => 'tab'),
		array('key' => 'field_pp_impact_sub', 'label' => 'Sub Title', 'name' => 'impact_sub_title', 'type' => 'text'),
		array('key' => 'field_pp_impact_title', 'label' => 'Title', 'name' => 'impact_title', 'type' => 'text'),
		array('key' => 'field_pp_impact_stats', 'label' => 'Impact Stats', 'name' => 'impact_stats', 'type' => 'repeater', 'sub_fields' => array(
			array('key' => 'field_pp_is_icon', 'label' => 'Icon Class', 'name' => 'icon_class', 'type' => 'text'),
			array('key' => 'field_pp_is_target', 'label' => 'Target Number', 'name' => 'target_number', 'type' => 'number'),
			array('key' => 'field_pp_is_suffix', 'label' => 'Suffix', 'name' => 'suffix', 'type' => 'text'),
			array('key' => 'field_pp_is_label', 'label' => 'Label', 'name' => 'label', 'type' => 'text'),
		)),
		
		array('key' => 'field_pp_tab_videos', 'label' => 'Videos Section', 'name' => '', 'type' => 'tab'),
		array('key' => 'field_pp_videos_sub', 'label' => 'Sub Title', 'name' => 'videos_sub_title', 'type' => 'text'),
		array('key' => 'field_pp_videos_title', 'label' => 'Title', 'name' => 'videos_title', 'type' => 'text'),
		array('key' => 'field_pp_videos', 'label' => 'Project Videos', 'name' => 'project_videos', 'type' => 'repeater', 'sub_fields' => array(
			array('key' => 'field_pp_pv_thumb', 'label' => 'Thumbnail', 'name' => 'thumbnail', 'type' => 'image', 'return_format' => 'array'),
			array('key' => 'field_pp_pv_url', 'label' => 'Video URL', 'name' => 'video_url', 'type' => 'text'),
			array('key' => 'field_pp_pv_title', 'label' => 'Title', 'name' => 'title', 'type' => 'text'),
		)),
		array('key' => 'field_pp_videos_viewall', 'label' => 'View All Link', 'name' => 'videos_view_all_link', 'type' => 'link', 'return_format' => 'array'),
		
		array('key' => 'field_pp_tab_cta', 'label' => 'CTA Section', 'name' => '', 'type' => 'tab'),
		array('key' => 'field_pp_cta_title', 'label' => 'Title', 'name' => 'cta_title', 'type' => 'text'),
		array('key' => 'field_pp_cta_desc', 'label' => 'Description', 'name' => 'cta_description', 'type' => 'textarea'),
		array('key' => 'field_pp_cta_primary', 'label' => 'Primary Button', 'name' => 'cta_primary_button', 'type' => 'link', 'return_format' => 'array'),
		array('key' => 'field_pp_cta_secondary', 'label' => 'Secondary Button', 'name' => 'cta_secondary_button', 'type' => 'link', 'return_format' => 'array'),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template/project-page.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_644bdfe9c87c5',
	'title' => 'Team',
	'fields' => array(
		array(
			'key' => 'field_644bdfea9d4c3',
			'label' => 'Members',
			'name' => 'members',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_644be08b9d4c5',
					'label' => 'Basic Info',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'parent_repeater' => 'field_644bdfea9d4c3',
					'selected' => 0,
				),
				array(
					'key' => 'field_644be00e9d4c4',
					'label' => 'Member Photo',
					'name' => 'member_photo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_644bdfea9d4c3',
				),
				array(
					'key' => 'field_644be30e9d4c6',
					'label' => 'Name',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Alex Maxwel',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_644bdfea9d4c3',
				),
				array(
					'key' => 'field_644be31e9d4c7',
					'label' => 'Designation',
					'name' => 'designation',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'CEO & Founder',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_644bdfea9d4c3',
				),
				array(
					'key' => 'field_644be32f9d4c8',
					'label' => 'About Texts',
					'name' => '',
					'aria-label' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'parent_repeater' => 'field_644bdfea9d4c3',
					'selected' => 0,
				),
				array(
					'key' => 'field_644be3419d4c9',
					'label' => 'Member Bio',
					'name' => 'member_bio',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam',
					'maxlength' => 220,
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
					'parent_repeater' => 'field_644bdfea9d4c3',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template/team.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_6a12d0ab39c8e',
	'title' => 'Theme Options',
	'fields' => array(
		array(
			'key' => 'field_6a12d0ab31ca0',
			'label' => 'Contact Informations',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a12d2b1f234a',
			'label' => 'Phone No 1',
			'name' => 'phone_no_1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '+919830725040',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a12d2d1f234b',
			'label' => 'Registered office',
			'name' => 'registered_office',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '9, Bompas Rd, Lake Market, Opposit CESE Office, Kolkata, West Bengal 700029',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a12d2e9f234c',
			'label' => 'Project Office',
			'name' => 'project_office',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Parnashree Green Heights Block 7 Flat 12 H 1476 Upen Banerjee Road Parnashee Kolkata 700060',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6a12d300f234d',
			'label' => 'Email Address',
			'name' => 'email_address',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'foundation.ramdhanu@gmail.com',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a12d33d16f69',
			'label' => 'Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a12d34716f6a',
			'label' => 'Footer Texts',
			'name' => 'footer_texts',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'children need your help start donating today',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6a12dd11827ba',
			'label' => 'Social Icons',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6a12dd4676403',
			'label' => 'Social Media Icons',
			'name' => 'social_media_icons',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6a12de2b7d487',
					'label' => 'Social Icon',
					'name' => 'social_icon',
					'aria-label' => '',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'all',
					),
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 1,
					'allow_in_bindings' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
					'parent_repeater' => 'field_6a12dd4676403',
				),
				array(
					'key' => 'field_6a12de5b7d488',
					'label' => 'Social Url',
					'name' => 'social_url',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a12dd4676403',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
) );
} );




?>